colordaysUntilStale: 60
colordaysUntilClose: 7
colorexemptLabels:
  - state-pinned
  - scope-security
colorstaleLabel: wontfix
colormarkComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
colorcloseComment: false
