name: JavaScript CI
on:
  push:
    branches: [ main, release-candidate/* ]
  pull_request:
    branches: [ main, release-candidate/* ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install git
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - name: Fetch Git Origin
      run: git fetch origin
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run Package Tests
      run: |
        npm ci
        npm test
  commit-message:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install git
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - name: Fetch Git Origin
      run: git fetch origin
    - name: Get Commit Message
      run: echo "::set-output name=subject::$(git log --format=%B -n 1 ${{ github.head_ref }})"
      id: log
  browserstack-test:
    runs-on: ubuntu-latest
    needs: commit-message
    if: "!startsWith( needs.commit-message.outputs.subject, 'Bump version to' )"
    steps:
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install git
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - name: Fetch Git Origin
      run: git fetch origin
    - name: Get Short SHA
      uses: benjlevesque/short-sha@v1.2
      id: short-sha
    - name: Get Tag Version
      uses: WyriHaximus/github-action-get-previous-tag@v1
      id: version
    - name: Create Staging Branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: staging/${{ steps.short-sha.outputs.sha }}
    - name: Checkout Staging Branch
      uses: actions/checkout@v2
      with:
        ref: staging/${{ steps.short-sha.outputs.sha }}
    - name: Switch Code Source to Github
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: /npm/material-dynmap
        replace: /gh/material-dynmap
        exclude: CHANGELOG.md|.*.json|.*.yml|.*.svg|java/.*
    - name: Switch Code to Staging Version
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "@v?${{ steps.version.output.value }}"
        replace: "@staging/${{ steps.short-sha.outputs.sha }}"
        exclude: CHANGELOG.md|.*.json|.*.yml|.*.svg|java/.*
    - name: Switch Assets to Staging Version
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: v${{ steps.version.output.value }}
        replace: staging/${{ steps.short-sha.outputs.sha }}
        exclude: CHANGELOG.md|*.json|*.yml|*.svg|java/**
    - name: BrowserStack Environment Setup
      uses: browserstack/github-actions/setup-env@master
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    - name: BrowserStack Local Tunnel Setup
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: staging/${{ steps.short-sha.outputs.sha }}
    - name: Run BrowserStack Tests
      run: node test/node.test.js
    - name: BrowserStack Local Stop
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop
